<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Configuration\**" />
    <Content Remove="Configuration\**" />
    <EmbeddedResource Remove="Configuration\**" />
    <None Remove="Configuration\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.2" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.4.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JSONAdminEditor.Application\JSONAdminEditor.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Pages\ContentVariables.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\CustomerEvents.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\CustomerSettings.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Dictionaries.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Error.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Events.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\PreferredCommunication.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Privacy.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Shared\_EventTabsPartial.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Shared\_Layout.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Shared\_ValidationScriptsPartial.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\TestAjax.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\_ViewImports.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\_ViewStart.cshtml" />
  </ItemGroup>

</Project>
